production:

  # AWS access key (required)
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>

  # AWS secret key (required)
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>

  # Bucket name (required)
  bucket: <%= ENV['S3_BUCKET'] %>

  # Identifier for the region in which the bucket was created (required)
  region: <%= ENV['S3_REGION'] %>

  # Folder name inside bucket where uploaded files should be stored (e.g. 'attachments')
  # The default behavior is to store data in the bucket's root directory
  # attachments_folder:

  # Folder where attachment thumbnails are stored
  # thumbnails_folder: thumbnails/

  # Whether objects are private, needing presigned URLs (default false)
  # private: true

development:
  # Copy configuration from `production` if desired

test:
  # Copy configuration from `production` if desired
